### ISSUE TITLE
Cover image written as JPEG, but PNG is required

### ISSUE THREAD

**Issue by attis** [haroldtreen/epub-press#13]
## Current Behavior

The cover image gets saved as `images/cover.png` and added to `ebook.opf` as:
```
<item id='cover-image' media-type='image/png' href='images/cover.png'/
```

Yet the file is actually a JPEG:
```
cover.png: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 816x1056, frames 3
```

This breaks showing book thumbnail on my PocketBook reader (all other readers don't seem to mind the mismatch)
## Expected Behavior

Cover should be set to `image/jpeg` media-type and saved as `cover.jpg`.

Thanks for all the work you're doing! I really appreciate EpubPress!

**Comment by attis** [comment]
OK, after some further investigation it looks like nodepub demands the cover to be PNG and does not support JPEGs so, I have updated the title to reflect that.
The solution seems straightforward. Since jimp determines output format based on filename extension, we should change `styling-service.js` to say
```
    static getTempFilename(book) {
        return `${book.getId()}.png`;
    }
```

If you'd like I can make a fork and a PR. Have also fixed some issues that prevented the project from running locally.

Let me know, thanks :)

**Comment by haroldtreen** [comment]
Hey @attis ! Thanks for the issue. If you have a fix I'd be delighted for a PR. 

Not sure when I'll have time to get to this but thanks for all the info. Should be able to fix from this!
