### ISSUE TITLE
Reddit suddenly not working 

### ISSUE THREAD

**Issue by gregschwartz** [haroldtreen/epub-press#17]
## Current Behavior
Sending tabs of Reddit posts doesn't work

## Expected Behavior
It used to, so perhaps Reddit put an IP block in for the EpubPress server?

## Steps to reproduce
1. Open tabs for Reddit entries, e.g.
- https://www.reddit.com/r/podcasting/comments/bqupor/weekly_episode_thread_20190520_share_your_podcast/
- https://www.reddit.com/r/podcasting/comments/bre34j/do_you_guys_know_if_there_is_any_kind_of_market/

or 

- https://www.reddit.com/r/HFY/comments/brejlx/humans_are_weird_a_good_long_walk/
- https://www.reddit.com/r/HFY/comments/bobpav/humans_are_weird_not_hiding/
- https://www.reddit.com/r/HFY/comments/bljce9/humans_are_weird_pardon_me_actual_story_with_this/ 

2. Verify all tabs have loaded.
3. Click extension
4. Select some or all tabs (doesn't matter)
5. Click Download
6. Check on Kindle: file loaded, but each chapter says:
  > We looked for content in [url] but couldn't find anything :(.
  >
  > Try making sure all your tabs have been fully loaded before downloding (sic) your book.
  >
  > Feel free to email [email] if you need help.

## System Information
Chrome Version 74.0.3729.157 (Official Build) (64-bit)
MacOS Mojave v10.14.3 Beta (18D39a)
Hardware: MacBook Pro Retina (Mid 2012)

**Comment by haroldtreen** [comment]
Hi Greg - thanks for the report! Maybe Reddit has restructured their HTML which has caused the element detection to stop working 🤔 ?

This could happen if they added something like:

```
<body id="ads">

</body>
```

EpubPress would just completely strip that out and not be able to find content (extreme example but something like that).

There's a test for reddit content - maybe it should be updated to check for a breakage...

**Comment by haroldtreen** [comment]
Found an issue that was stripping a bunch of divs - should be extracting stuff again. 👍

**Comment by gregschwartz** [comment]
Woohoo, it is indeed working! Thanks :)
