### ISSUE TITLE
Support custom coverPaths

### ISSUE THREAD

**Issue by haroldtreen** [haroldtreen/epub-press#38]
## Current Behavior

- When a user publishes a book the cover is hardcoded to the EpubPress logo.
- There's no way to pass the url to an image to use instead.

## Expected Behavior

- A user should be able to send `coverPath` in the request body.
- The provided image should be read and used for the cover of the book.

## Steps to reproduce

- Run EpubPress locally
- Make a request with `coverPath` in the body
```
curl --X POST 'http://localhost:3000/api/v1/books' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
-d '{
    "title": "This is the title",
    "description": "This is the description",
    "coverPath": "https://via.placeholder.com/816x1056.jpg?text=CoverPage",
    "urls": [
        "https://epub.press/"
    ]
}'
```
- The resulting book should contain the provided image as the cover.

**Comment by wrobbins** [comment]
The add text to cover step should be skipped when a coverPath is provided.
