### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by TaiPhamD** [haroldtreen/epub-press#70]
Do you think we can add an optional parameter called sectionTitles: [ ] where the epub-press would override the auto parsed section title based on the array passed in?  I often run into issues where the auto parsed title isn't what I want but I can easily fix it if I can pass in my own title array. We could make it so that the sectionTitles and the URL count matches if sectionTitles is non-empty. I could create a PR for this as well.

```
{
    "title": "A title",
    "description": "A description",
    "author": "An author",
    "genre": "ebooks",
    "coverPath": "",
    "sectionTitles": [ ] <--Optional
    "urls": [
        "https://epub.press"
    ]
}
```

**Comment by TaiPhamD** [comment]
oh never mind I look at the swagger api and found that this feature is already available in the sections property. 

{
  "author": "string",
  "coverPath": "string",
  "description": "string",
  "genre": "string",
  "language": "string",
  "published": "string",
  "publisher": "string",
  "sections": [
    {
      "content": "string",
      "title": "string"
    }
  ],
  "series": "string",
  "sequence": 0,
  "urls": [
    "string"
  ]
}

**Comment by TaiPhamD** [comment]
I tried using the sections but it's not working for me.

{
    "title": "Book1 Test",
    "description": "description 1",
    "author": "Author1",
    "genre": "ebooks",
    "coverPath": "",
    "sections": [{"content": "<!DOCTYPE html><html><head>Hello world</head><body>my story</body></html>",
                 "title":"Hello world"}]
}

this is my sample payload but I am not able to get a proper book download. Is the content supposed to the the html page as as a string or the html url?

**Comment by wrobbins** [comment]
@TaiPhamD I think #71 addresses your this feature request.
