### ISSUE TITLE
Kindle will no longer support MOBI via email delivery, but will support EPUB

### ISSUE THREAD

**Issue by blaenk** [haroldtreen/epub-press#84]
You've probably already seen this, but just in case, I just received an email containing this:

> Dear Kindle Customer,
> 
> Thank you for using the Send to Kindle service to send personal documents to your Kindle library. We wanted to let you know that starting August 2022, you’ll no longer be able to send MOBI (.mobi, .azw) files to your library. Any MOBI files already in your Kindle library will not be affected by this change.
> 
> MOBI is an older file format and won’t support the newest Kindle features for documents. Any existing MOBI files you want to read with our most up-to-date features for documents will need to be re-sent in [a compatible file format](https://www.amazon.com/gp/help/customer/display.html).
> 
> Also, compatible formats now include EPUB (.epub), which you can send to your library using your Send to Kindle email address. We’ll also be adding EPUB support to the free Kindle app for iOS and Android devices and the Send to Kindle desktop app for PC and Mac.
> 
> If you have any questions, please visit our help page or contact our Customer Service team.
> 
> Regards,
> The Kindle Team

It seems like it should be safe to switch to sending EPUB globally right now since their service appears to convert to KFX/AZW3 on receipt anyway, that is, it doesn't appear that Kindle itself natively supports reading EPUB files. [Source](https://goodereader.com/blog/kindle/the-amazon-kindle-will-support-epub-in-late-2022).

This may involve undoing/changing work that was previously done by https://github.com/haroldtreen/epub-press/pull/6 (and possibly others since then, of course).

More information in [this thread](https://www.mobileread.com/forums/showthread.php?t=346530). Apparently EPUB was always supported but users had to "hide" that it was EPUB by giving it a different file extension e.g. `.png`, and so it appears that now all that has changed is that the `.epub` file extension is "allowed".

**Comment by sanujar** [comment]
Saw this myself on goodereader but it didn't have a source there. Saw the
email myself after this one. Guess this is good news overall, really. If
only I'd made my PR earlier.

Should help with those trying to get this to work on ARM too when taking
out all those external dependencies.

The official support page says EPUB will be supported from late 2022, but
it's also already on the supported list. Wonder whether it's actually
properly accepted, and just how good the official conversion is.

**Comment by blaenk** [comment]
Yup it turns out it already works via email, you can confirm by trying it yourself or checking some comments in the mobileread thread I linked. I think the mentioned date is for the Send to Kindle app itself.

**Comment by haroldtreen** [comment]
Oh wow! Thanks for the heads up @blaenk ! 

Was about to say that it's probably fine to leave the `.mobi` stuff and leave it to users to switch - but that old PR would definitely cause issues 😅. I'll make a point of flipping it so that `.epub` is used 🎉.

**Comment by haroldtreen** [comment]
Should be updated to force `.epub` for all `kindle` emails 👍.

Thanks for raising this!
